/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Note = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'isUnlocked' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getCurrentDay' : IDL.Func([], [IDL.Int], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'initializeAndGetDay' : IDL.Func([], [IDL.Int], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Note = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'isUnlocked' : IDL.Bool,
  });
  
  return IDL.Service({
    'getCurrentDay' : IDL.Func([], [IDL.Int], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'initializeAndGetDay' : IDL.Func([], [IDL.Int], []),
  });
};

export const init = ({ IDL }) => { return []; };